# Gym-Mountain_Car

Issues:
Traceback (most recent call last):
  File "C:\Users\Xi Chen\Documents\Resume Data Science Projects\Qmind\Onboarding Assignment\Mountain Car Test.py", line 15, in <module>
    from rl.agents.dqn import DQNAgent
  File "C:\Users\Xi Chen\anaconda3\envs\dlenv\Lib\site-packages\rl\agents\__init__.py", line 1, in <module>
    from .dqn import DQNAgent, NAFAgent, ContinuousDQNAgent
  File "C:\Users\Xi Chen\anaconda3\envs\dlenv\Lib\site-packages\rl\agents\dqn.py", line 7, in <module>
    from rl.core import Agent
  File "C:\Users\Xi Chen\anaconda3\envs\dlenv\Lib\site-packages\rl\core.py", line 7, in <module>
    from rl.callbacks import (
  File "C:\Users\Xi Chen\anaconda3\envs\dlenv\Lib\site-packages\rl\callbacks.py", line 8, in <module>
    from tensorflow.keras import __version__ as KERAS_VERSION
ImportError: cannot import name '__version__' from 'tensorflow.keras' (C:\Users\Xi Chen\anaconda3\envs\dlenv\Lib\site-packages\keras\api\_v2\keras\__init__.py)
